M48
; DRILL file {KiCad 8.0.5-8.0.5-0~ubuntu24.04.1} date 2024-09-23T15:55:13+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-23T15:55:13+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-8.0.5-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,8,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X110.5Y-94.0
X110.5Y-130.0
X154.5Y-94.0
X154.5Y-130.0
M30
